In [1]:
Import numpy as np

SyntaxError: invalid syntax (<ipython-input-1-5f8f38d20256>, line 1)

In [2]:
import numpy as np
#import pandas as pd

In [3]:
#rank 1 array

arr1=[2,4,5,8,9]

print(type(arr1))

<class 'list'>


In [4]:
narr1=np.array(arr1)

In [5]:
print(type(narr1))

<class 'numpy.ndarray'>


In [6]:
#multidimensional array

arr2=[[2,3,4,5],[7,8,9,10]]

narr2=np.array(arr2)

print(narr2)

[[ 2  3  4  5]
 [ 7  8  9 10]]


In [7]:
#multidimensional array 3 rows

arr3=[[2,3,4,5],[7,8,9,10],[1,3,5,7]]

narr3=np.array(arr3)

print(narr3)

[[ 2  3  4  5]
 [ 7  8  9 10]
 [ 1  3  5  7]]


In [8]:
print(narr3.shape) #menghitung jumlah baris dan kolom

(3, 4)


In [10]:
#2*2 array with zero's

zer=np.zeros((2,2))

print(zer)

[[0. 0.]
 [0. 0.]]


In [11]:
#2*2 array with 5

full=np.full((2,2),5)

print(full)

[[5 5]
 [5 5]]


In [12]:
#diagonal 1

ex3=np.eye(2,2)
print(ex3)

[[1. 0.]
 [0. 1.]]


In [13]:
#diagonal 1

ex4=np.eye(4,4)
print(ex4)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# Basic Numpy Operations

In [14]:
import numpy as np

In [15]:
a=[1,2,11,6,8,18,2] #python memulai indeks dari kiri 0 hingga 7 dan minus -7 dari kiri ke -1

na=np.array(a)

print(a)

[1, 2, 11, 6, 8, 18, 2]


In [16]:
print(na.shape) #rank 1 dengan 7 kolom

(7,)


In [17]:
#print element pada indeks 2
print(na[2])

11


In [18]:
print(na[1:5]) #print indeks 1 sampai 5

[ 2 11  6  8]


In [19]:
print(na[1:5:2]) #print indeks 1 sampai 5 dengan 2 angka indeks

[2 6]


In [20]:
#negative indeks
print(na[-7:-3]) #print indeks 1 sampai 4

[ 1  2 11  6]


In [21]:
#print indeks terakhir
print(na[-1])

2


In [22]:
#prints mulai indeks 3 sampai terakhir
print(a[3:])

[6, 8, 18, 2]


In [23]:
#prints indeks awal sampai indeks 4
print(a[:4])

[1, 2, 11, 6]


In [25]:
b=a[:] #copy numpy array
print(b)

[1, 2, 11, 6, 8, 18, 2]


In [27]:
#concetanate atau menyatukan 2 numpy array

x=np.array([2,4,6,8])
y=np.array([1,3,5,7])

z=np.concatenate([x,y])

print(z)

[2 4 6 8 1 3 5 7]


# multidimensional array

In [28]:
arr=[[1,2,3,4],[3,4,5,6],[5,6,7,8],[7,8,9,10],[2,4,6,8]]

narr=np.array(arr) #konversi ke dalam bentuk arrray

print(narr)

[[ 1  2  3  4]
 [ 3  4  5  6]
 [ 5  6  7  8]
 [ 7  8  9 10]
 [ 2  4  6  8]]


In [29]:
#print baris 1 pada indeks 0

print(narr[0])

[1 2 3 4]


In [30]:
#print baris 3 pada indeks 2

print(narr[2])

[5 6 7 8]


In [32]:
print(narr[2,3]) #print baris 3 pada indeks 2 dengan kolom 4 pada indeks 3

8


In [34]:
narr[3,0]=14 #mengganti baris 4 pada indeks 3 dengan kolom 1 pada indeks 0

print(narr)

[[ 1  2  3  4]
 [ 3  4  5  6]
 [ 5  6  7  8]
 [14  8  9 10]
 [ 2  4  6  8]]


In [35]:
#print baris terakhir

print(narr[-1])

[2 4 6 8]


In [36]:
#print baris kedua dari terakhir

print(narr[-2])

[14  8  9 10]


In [38]:
#print baris dan kolom

print(narr[1:3,3:5])

[[6]
 [8]]


In [44]:
#menggabungkan baris dan kolom

f=np.array([[1,2],[3,4]])
g=np.array([[5,6]])

h=np.concatenate((f,g))

print(h)

[[1 2]
 [3 4]
 [5 6]]


# Vector Aritmethic

In [12]:
import numpy as np

In [13]:
#membuat array

x = np.array([1,2,3])
y = np.array([4,5,6])

# # Addition

In [14]:
print(x+y)

[5 7 9]


In [15]:
print(x+2) #scalar addition

[3 4 5]


In [16]:
print(y-x) #substract

[3 3 3]


In [17]:
print(x*y) #hadmard product

[ 4 10 18]


In [18]:
print(np.dot(y,x)) #dot product

32


In [19]:
print(y/x)

[4.  2.5 2. ]


## Matrix Aritmatika

In [20]:
import numpy as np

In [21]:
xp=np.matrix([[1,2],[3,4]])
yp=np.matrix([[5,6],[7,8]])

#numpy matrix itu 2 dimensi, sedangkan numpy arrays N-dimensi

In [23]:
print(type(yp)) #cek type

<class 'numpy.matrix'>


In [24]:
print(xp+yp) #addition

[[ 6  8]
 [10 12]]


In [25]:
print(xp+4) #addition

[[5 6]
 [7 8]]


In [26]:
print(yp-xp) #substract

[[4 4]
 [4 4]]


In [27]:
print(xp*yp) #scalar

[[19 22]
 [43 50]]


### Multiplication

In [28]:
A=np.matrix([[1,2],[3,4]])

print(A)

[[1 2]
 [3 4]]


In [29]:
print(A*A) #hadmard multiplication

[[ 7 10]
 [15 22]]


In [30]:
print(np.multiply(A,A)) #element wise multiplication atau dikalikan matriks yang sama

[[ 1  4]
 [ 9 16]]


In [31]:
from numpy.linalg import inv

In [32]:
print(inv(A)) #inverse matriks, rumus = 1/ad-bc dikalikan matriks d -b -c a > 1/-0.5 dikalikan 4 -2 -3 1

[[-2.   1. ]
 [ 1.5 -0.5]]


In [33]:
print(A.T) #transpose matriks, dibalik menjadi a c b d atau baris menjadi kolom dan sebaliknya

[[1 3]
 [2 4]]


# Broadcasting

menampilkan aritmatika pada perbedaan bentuk arrays
peraturan :
(1) satu dimensi (1D) harus mempunyai isi dimensi yang sama dalam baris atau kolomnya misal 1 baris berisi (1,2,3) dan baris kedua juga (1,2,3) untuk kedua array. array adalah baris atau kolom
(2) dimensi array yang kecil harus menjadi 1D array

In [34]:
import numpy as np

In [36]:
B=np.arange(20).reshape(5,4) #membuat matriks dengan angka 0 sampai 20 atau 19 dengan jumlah baris baris 5 dan kolom 4
print(B)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [37]:
print(type(B))

<class 'numpy.ndarray'>


In [38]:
C=np.arange(5) #matriks dengan 5 kolom
print(C)

[0 1 2 3 4]


In [40]:
C=C.reshape(5,1) #untuk menghitung matriks B dan C harus disesuaikan dan baris disesuaikan menjadi 5 karna sebelumnya C memiliki 1 baris dan 5 kolom
print(C)

[[0]
 [1]
 [2]
 [3]
 [4]]


In [41]:
print(B*C) #mengalikan matriks B dan C

[[ 0  0  0  0]
 [ 4  5  6  7]
 [16 18 20 22]
 [36 39 42 45]
 [64 68 72 76]]


# Menyelesaikan equation

In [42]:
import numpy as np

In [43]:
m=np.array([[1,3],[5,7]])
print(m)

[[1 3]
 [5 7]]


In [44]:
n=np.array([3,-1])
print(n)

[ 3 -1]


In [45]:
minv=np.linalg.inv(m) #menyelesaikan linear matriks equation, atau scalar linear sistem equation
print(minv)

[[-0.875  0.375]
 [ 0.625 -0.125]]


In [46]:
minv.dot(n) #x = -3 y = 2

array([-3.,  2.])

In [48]:
np.linalg.solve(m,n) #menyelesaikan linear sistem equation > x = -3 yaitu x = m^-1*n, sama dengan minv.dot, m^ adalah minv

array([-3.,  2.])

# statistik dengan numpy

In [61]:
arr=[[1,2,3,4],[3,4,5,6],[5,6,7,8],[7,8,9,10],[2,4,6,8]]

narr=np.array(arr) #konversi ke dalam bentuk arrray

print(narr)

[[ 1  2  3  4]
 [ 3  4  5  6]
 [ 5  6  7  8]
 [ 7  8  9 10]
 [ 2  4  6  8]]


In [63]:
narr.sum() #menjumlahkan total seluruh array

108

In [65]:
narr.sum(axis=0) #axis 0 adalah kolom dan dijumlahkan total keempat kolom

array([18, 24, 30, 36])

In [66]:
narr.sum(axis=1) #axis 1 adalah baris dan dijumlahkan kelima baris

array([10, 18, 26, 34, 20])

In [67]:
narr.mean(axis=0) #mencari mean atau nilai tengah

array([3.6, 4.8, 6. , 7.2])

In [70]:
np.median(narr,axis=1) #mencari median harus menggunakan numpy

array([2.5, 4.5, 6.5, 8.5, 5. ])

In [71]:
np.std(narr) #mencari standar deviasi atau varians

2.4576411454889016

In [72]:
np.percentile(narr,50) #mencari percentile 50

5.5